Pipe Testv2

diff --git a/buildspec_sonar.yml b/buildspec_sonar.yml
--- a/buildspec_sonar.yml
+++ b/buildspec_sonar.yml
@@ -1,29 +1,39 @@
 version: 0.2
 env:
   secrets-manager:
-    LOGIN: x23267801_SonarCred:SONAR_TOKEN
+    SONARCLOUD_TOKEN: x23267801_SonarCred:SONAR_TOKEN
+    PROJECTKEY: x23267801_SonarCred:SONAR_PROJECT_KEY
+    SONARCLOUD_ORG: x23267801_SonarCred:SONAR_ORG_KEY
     HOST: x23267801_SonarCred:HOST
-    Organization: x23267801_SonarCred:SONAR_ORG_KEY
-    Project: x23267801_SonarCred:SONAR_PROJECT_KEY
+    
 phases:
   install:
     runtime-versions:
-      java: openjdk8
-  pre_build:
+      java: corretto21
     commands:
-      - apt-get update
-      - apt-get install -y jq
-      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
-      - tar xzf apache-maven-3.5.4-bin.tar.gz
-      - ln -s apache-maven-3.5.4 maven
-      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
-      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
-      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
+      - yum update -y
+      - yum install -y jq
+      - retry_count=3
+      - for i in $(seq 1 $retry_count); do wget https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz && break || sleep 10; done
+      - tar xzf apache-maven-3.8.6-bin.tar.gz || true
+      - ln -s apache-maven-3.8.6 maven
+      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
+      - unzip ./sonar-scanner-cli-4.8.0.2856-linux.zip
+      - mv sonar-scanner-4.8.0.2856-linux /sonar-scanner
+      - export PATH=$PATH:/sonar-scanner/bin/
+ 
   build:
     commands:
-      - mvn test     
-      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
+      - find / -name pom.xml -exec mv {} ./pom.xml \; || true
+      - mvn sonar:sonar -Dsonar.login=$SONARCLOUD_TOKEN -Dsonar.host.url=$HOST -Dsonar.projectKey=$PROJECTKEY -Dsonar.organization=$SONARCLOUD_ORG
       - sleep 5
-      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
-      - cat result.json
-      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
+      - response_code=$(curl -s -o /dev/null -w "%{http_code}" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECTKEY")
+      - if [ "$response_code" -ne 200 ]; then
+          echo "Quality Gate check failed with HTTP code $response_code";
+          exit 1;
+        fi
+ 
+artifacts:
+  files:
+    - 'target/*.jar'
+    - 'logs/**'
